services:
  - type: web
    name: ai-faq-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.run:app -w 2 -b 0.0.0.0:10000
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false