name: Deploy AI FAQ App to Cloudflare Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # *** SET THE DEFAULT WORKING DIRECTORY FOR ALL STEPS HERE ***
    defaults:
      run:
        working-directory: ./ai-faq-app
        
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- Install Dependencies Step ---
      - name: Install Dependencies
        run: npm install

      # --- Build Project Step ---
      - name: Build Project
        run: npm run build 

      # --- DEPLOYMENT ---
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          projectName: ai-faq-assistant 
          
          # The output directory should now be relative to the new working-directory path
          directory: ./.vercel/output/static 
          
          # Since the working directory is now inside the subfolder, this deployment directory 
          # must be relative to that (which the build command should create).
          # If this step fails, the error log should tell us the correct output folder name!
