name: Deploy AI FAQ App to Cloudflare Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # We will remove the defaults: run: working-directory to use a custom path later
    
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # =================================================================
      # *** NEW DEBUG STEP ***
      # This step will print the current location and contents of the folder.
      # Look for the "package.json" file in the log to find its true path.
      # =================================================================
      - name: Find the Correct Working Directory
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -aR 
          
      # The remaining steps are currently commented out to allow the debug log to run and fail cleanly
      - name: Install Dependencies
        # This step will fail, but the one before it should give us the answer!
        run: echo "Skipping install for debug..." && exit 0

      - name: Build Project
        run: echo "Skipping build for debug..." && exit 0
        
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          projectName: ai-faq-assistant 
          directory: ./dist # Temporary path
