name: Deploy AI FAQ App to Cloudflare Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # *** CORRECTED WORKING DIRECTORY PATH ***
    # This tells the system to step into the nested project folder.
    defaults:
      run:
        working-directory: ./ai-faq-app/ai-faq-app
        
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- Install Dependencies Step (Should now find package.json) ---
      - name: Install Dependencies
        run: npm install

      # --- Build Project Step ---
      - name: Build Project
        run: npm run build 

      # --- DEPLOYMENT ---
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          projectName: ai-faq-assistant-final 
          
          # The output directory relative to the new working directory (./ai-faq-app/ai-faq-app)
          directory: ./.vercel/output/static
