name: Deploy AI FAQ App to Cloudflare Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # *** SET THE DEFAULT WORKING DIRECTORY FOR ALL STEPS HERE ***
    # This assumes the checkout action creates one single subfolder with the repo name.
    defaults:
      run:
        working-directory: ./ai-faq-app 
        
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Debug Current Directory
        run: pwd && ls -a
      # --- Install Dependencies Step (Now running inside ./ai-faq-app) ---
      - name: Install Dependencies
        run: npm install

      # --- Build Project Step ---
      - name: Build Project
        run: npm run build 

      # --- DEPLOYMENT ---
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          projectName: ai-faq-assistant 
          
          # The output directory must be relative to the new working-directory path
          # which is: ./ai-faq-app/.vercel/output/static
          directory: ./.vercel/output/static
