name: Deploy AI FAQ App to Cloudflare Pages

on:
  push:
    branches:
      # This means the deployment will run every time you push to the 'main' branch
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Required GitHub permissions for deployment
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- 1. SETUP & BUILD ---
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # This runs the standard Next.js or similar build command
      - name: Build Project
        run: npm run build 

      # --- 2. DEPLOYMENT (Using your CLOUDFLARE secrets) ---
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          # Account ID and API Token from GitHub Secrets
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          # 1. Project Name (The name you want on Cloudflare)
          projectName: ai-faq-assistant 
          
          # 2. Output Directory (The required output for Vercel/Next.js migration)
          directory: .vercel/output/static
