name: Deploy AI FAQ App to Cloudflare Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- Install Dependencies Step (CORRECTED) ---
      - name: Install Dependencies
        # This line tells the action where to find package.json
        working-directory: ./ai-faq-app 
        run: npm install

      # --- Build Project Step (CORRECTED) ---
      - name: Build Project
        # This line ensures the build command runs in the correct folder
        working-directory: ./ai-faq-app 
        run: npm run build 

      # --- DEPLOYMENT (No changes here, but confirming the directory) ---
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          projectName: ai-faq-assistant 
          
          # This should still be correct if your project is Next.js/Vite in that sub-folder
          directory: ./ai-faq-app/.vercel/output/static
